export const MODAL_STYLES = {
  dialog: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '8px 0px',
    gap: '8px',
    width: '1080px',
    maxWidth: '90vw',
    maxHeight: '90vh',
    background: '#FFFFFF',
    boxShadow: '0px 0px 0px 1px rgba(18,18,23,0.1), 0px 24px 48px rgba(18,18,23,0.03), 0px 10px 18px rgba(18,18,23,0.03), 0px 5px 8px rgba(18,18,23,0.04), 0px 2px 4px rgba(18,18,23,0.04)',
    borderRadius: '8px',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },

  header: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 20px 16px',
    gap: '20px',
    width: '100%',
    height: '64px',
    borderBottom: '1px solid #E8EAEF',
    flexShrink: 0,
    alignSelf: 'stretch',
  },

  title: {
    margin: 0,
    fontFamily: 'Inter, sans-serif',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: '28px',
    color: '#121217',
    flexShrink: 0,
  },

  tabBar: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '0px 20px',
    gap: '10px',
    isolation: 'isolate',
    width: '100%',
    height: '48px',
    borderBottom: '1px solid #E8EAEF',
    flexShrink: 0,
    alignSelf: 'stretch',
  },

  tabContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '20px 20px 24px',
    gap: '20px',
    width: '100%',
    background: 'rgba(18, 18, 23, 0.02)',
    flex: 1,
    overflow: 'auto',
    alignSelf: 'stretch',
    boxSizing: 'border-box',
  },

  field: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: '0px',
    gap: '8px',
    height: '72px',
    borderRadius: '0px',
    flex: 1,
    boxSizing: 'border-box',
  },

  footer: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px 12px',
    gap: '10px',
    width: '100%',
    height: '68px',
    flexShrink: 0,
    alignSelf: 'stretch',
    background: '#FFFFFF',
  },

  btnGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '0px',
    gap: '10px',
    height: '40px',
  },

  btnCancel: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '8px 12px',
    width: '100px',
    height: '40px',
    background: '#FFFFFF',
    border: '1px solid #D1D4DB',
    boxShadow: '0px 1px 2px rgba(18, 18, 23, 0.05)',
    borderRadius: '360px',
    fontSize: '14px',
    fontWeight: 500,
    color: '#121217',
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
  },

  btnSaveDisabled: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '8px 12px',
    width: '158px',
    height: '40px',
    background: '#D1D4DB',
    borderRadius: '360px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 500,
    color: '#FFFFFF',
    cursor: 'not-allowed',
    fontFamily: 'Inter, sans-serif',
  },

  btnSaveEnabled: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '8px 12px',
    width: '158px',
    height: '40px',
    background: '#121217',
    borderRadius: '360px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 500,
    color: '#FFFFFF',
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
  },
};
