import { useRef, useEffect, useState } from 'react';
import { X, Printer } from 'lucide-react';

// Inline report CSS (matches templates/reports/base.css)
const REPORT_CSS = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 10pt; color: #1e293b; line-height: 1.4; }
  .report-container { padding: 20mm 15mm; }
  .report-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8mm; padding-bottom: 4mm; border-bottom: 2px solid #1a1a2e; }
  .report-title { font-size: 16pt; font-weight: 700; color: #1a1a2e; }
  .report-meta { text-align: right; font-size: 8pt; color: #64748b; }
  .report-table { width: 100%; border-collapse: collapse; font-size: 9pt; }
  .report-table thead th { background: #f8fafc; border-bottom: 2px solid #e2e8f0; padding: 2mm 3mm; text-align: left; font-weight: 600; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; white-space: nowrap; }
  .report-table tbody td { padding: 1.5mm 3mm; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
  .report-table tbody tr:nth-child(even) { background: #f1f5f9; }
  .cell-boolean { text-align: center; }
  .cell-boolean .yes { color: #16a34a; font-weight: 600; }
  .cell-boolean .no { color: #64748b; }
  .cell-amount { text-align: right; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 8.5pt; }
  .report-footer { margin-top: 6mm; padding-top: 3mm; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; font-size: 8pt; color: #64748b; }
  .report-summary { font-weight: 600; color: #1e293b; }
  @page { margin: 15mm; size: A4 portrait; }
  @media print { .report-container { padding: 0; } }
`;

function formatValue(value, type) {
  if (value == null) return '';
  if (type === 'boolean') {
    return value
      ? '<span class="yes">Yes</span>'
      : '<span class="no">No</span>';
  }
  if (type === 'amount' || type === 'number') {
    const num = Number(value);
    if (isNaN(num)) return String(value);
    return new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(num);
  }
  if (type === 'date' || type === 'datetime') {
    const d = new Date(value);
    if (isNaN(d.getTime())) return String(value);
    return new Intl.DateTimeFormat('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);
  }
  return String(value);
}

function buildReportHtml(title, columns, data) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' });

  const headerCells = columns
    .map(col => `<th style="width: ${col.width || 'auto'}">${col.header || col.accessorKey || col.id || ''}</th>`)
    .join('');

  const bodyRows = data.map(row => {
    const cells = columns.map(col => {
      const key = col.accessorKey || col.id;
      const val = row[key];
      const type = col.meta?.type || 'string';
      const cellClass = type === 'boolean' ? 'cell-boolean' : (type === 'amount' || type === 'number') ? 'cell-amount' : '';
      return `<td class="${cellClass}">${formatValue(val, type)}</td>`;
    }).join('');
    return `<tr>${cells}</tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><style>${REPORT_CSS}</style></head>
<body><div class="report-container">
  <div class="report-header">
    <div><div class="report-title">${title}</div></div>
    <div class="report-meta"><div>${now}</div></div>
  </div>
  <table class="report-table">
    <thead><tr>${headerCells}</tr></thead>
    <tbody>${bodyRows}</tbody>
  </table>
  <div class="report-footer">
    <div class="report-summary">Total: ${data.length} records</div>
    <div>Generated by Etendo Go</div>
  </div>
</div></body></html>`;
}

export default function ReportDrawer({ open, onClose, windowName, columns, data, title }) {
  const iframeRef = useRef(null);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    if (!open || !iframeRef.current) {
      setReady(false);
      return;
    }
    const html = buildReportHtml(title || windowName || 'Report', columns || [], data || []);
    const doc = iframeRef.current.contentDocument;
    doc.open();
    doc.write(html);
    doc.close();
    setReady(true);
  }, [open, columns, data, title, windowName]);

  const handlePrint = () => {
    if (iframeRef.current?.contentWindow) {
      iframeRef.current.contentWindow.print();
    }
  };

  if (!open) return null;

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/30 z-40 transition-opacity"
        onClick={onClose}
      />

      {/* Drawer */}
      <div className="fixed right-0 top-0 bottom-0 w-[65%] max-w-4xl bg-white shadow-2xl z-50 flex flex-col animate-in slide-in-from-right duration-200">
        {/* Toolbar */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border/30 bg-slate-50 shrink-0">
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-semibold text-foreground">{title || windowName || 'Report'}</h2>
            <span className="text-xs text-muted-foreground">{(data || []).length} records</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              disabled={!ready}
              className="inline-flex items-center gap-1.5 h-8 px-3 rounded-lg text-xs font-medium bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50 transition-colors"
            >
              <Printer className="h-3.5 w-3.5" />
              Print / Save PDF
            </button>
            <button
              onClick={onClose}
              className="h-8 w-8 flex items-center justify-center rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Preview */}
        <div className="flex-1 overflow-hidden bg-slate-100 p-4">
          <div className="bg-white rounded-lg shadow-lg h-full overflow-hidden">
            <iframe
              ref={iframeRef}
              title="Report Preview"
              className="w-full h-full border-0"
            />
          </div>
        </div>
      </div>
    </>
  );
}
