// Update this file to improve the classification
export const DEFAULT_BOUNDARY_POLICY = {
  verticalWindows: {
    sales: [
      'sales',
      'sales-order',
      'sales-invoice',
      'sales-quotation',
      'goods-shipment',
      'return-from-customer',
      'print-sales-order',
      'print-sales-invoice',
      'print-sales-quotation',
      'print-goods-shipment',
    ],
    purchases: [
      'purchases',
      'purchase-order',
      'purchase-invoice',
      'goods-receipt',
      'return-to-vendor',
      'return-to-vendor-shipment',
      'return-material-receipt',
      'print-purchase-order',
    ],
    inventory: [
      'inventory',
      'physical-inventory',
      'warehouse',
      'warehouse-picking-list',
      'warehouse-storage-bins',
      'goods-movements',
      'internal-consumption',
      'inventory-quality-inspection',
      'inventory-stock-report',
      'stock-reservation',
      'product',
      'product-category',
      'unit-of-measure',
      'uom',
      'packing',
      'bom-production',
    ],
    fiscal: [
      'fiscal-config',
      'fiscal-monitor',
      'fiscal-models',
      'sii-config',
      'sii-monitor',
      'tbai-config',
      'tbai-facturas-enviadas',
      'verifactu-config',
      'monitor-verifactu',
      'tax',
      'tax-report',
    ],
    finance: [
      'accounting',
      'balance-sheet',
      'bank-reconciliation',
      'chart-of-accounts',
      'payment-in',
      'payment-out',
      'payment-method',
      'payment-term',
      'profit-loss',
      'report-general-ledger',
      'report-journal-entries',
      'report-trial-balance',
      'aging-payable',
      'aging-receivable',
      'cost-adjustment',
      'commission',
      'commission-payment',
      'price-list',
      'landed-cost',
    ],
    'people-crm': [
      'absence',
      'activity',
      'business-partner',
      'contacts',
      'crm',
      'deal',
      'employee',
      'hr',
      'lead',
      'project',
      'projects',
      'time-tracking',
      'user',
      'bp-location',
    ],
  },
  windowDocPattern: '^docs/generated-custom-windows/([a-z0-9-]+)\\.md$',
  e2eFlowPattern: '^e2e/tests/flows/(.+)\\.(?:mocked\\.)?spec\\.js$',
  crossDomainPlanPattern: '^docs/plans/[^/]+-cross-domain\\.md$',
  repoDocPatterns: [
    '^docs/(?:architecture|ops|diagrams|proposals|superpowers|plans)/',
    '^docs/[^/]+\\.md$',
  ],
  patternGroups: [
    {
      id: 'generator',
      kind: 'generator-change',
      scope: 'generator-change',
      patterns: [
        '^cli/package(?:-lock)?\\.json$',
        '^cli/src/generate-',
        '^cli/src/extract-',
        '^cli/src/resolve-curated\\.js$',
        '^cli/src/pipeline\\.js$',
        '^cli/src/run-[a-z0-9-]+-tests\\.js$',
        '^cli/src/regen-all\\.js$',
        '^cli/src/push-to-neo\\.js$',
        '^cli/src/validate-',
        '^cli/src/migrate-',
        '^cli/src/migrations/',
        '^cli/src/quality-gate(?:\\.js|/)',
        '^cli/test/',
        '^schemas/',
        '^templates/',
        '^core-maps/',
        '^quality-gate\\.config\\.json$',
        '^cli/config/regen-windows\\.json$',
      ],
    },
    {
      id: 'sdk',
      kind: 'sdk-or-external-app',
      scope: 'sdk-or-external-app',
      patterns: [
        '^packages/apps-sdk(?:-|/)',
        '^tools/quick-order-app/',
        '^tools/spike-hello-app/',
      ],
    },
    {
      id: 'app-shell-core',
      kind: 'app-shell-core',
      scope: 'app-shell-core',
      patterns: ['^packages/app-shell-core/'],
    },
    {
      id: 'platform',
      kind: 'platform-change',
      scope: 'platform-change',
      patterns: [
        '^tools/app-shell/package(?:-lock)?\\.json$',
        '^tools/app-shell/src/App\\.jsx$',
        '^tools/app-shell/src/main\\.jsx$',
        '^tools/app-shell/src/index\\.css$',
        '^tools/app-shell/src/menu\\.json$',
        '^tools/app-shell/src/test/',
        '^tools/app-shell/test/',
        '^tools/app-shell/src/components/[^/]+\\.(?:js|jsx)$',
        '^tools/app-shell/src/components/__tests__/',
        '^tools/app-shell/src/components/attachments/',
        '^tools/app-shell/src/components/copilot/',
        '^tools/app-shell/src/components/dashboard/',
        '^tools/app-shell/src/components/layout/',
        '^tools/app-shell/src/components/related-documents/',
        '^tools/app-shell/src/components/contract-ui/',
        '^tools/app-shell/src/components/ui/',
        '^tools/app-shell/src/explorer/',
        '^tools/app-shell/src/hooks/',
        '^tools/app-shell/src/auth/',
        '^tools/app-shell/src/layout/',
        '^tools/app-shell/src/i18n/',
        '^tools/app-shell/src/locales/',
        '^tools/app-shell/src/pages/',
        '^tools/app-shell/src/preview/',
        '^tools/app-shell/src/windows/__tests__/',
        '^tools/app-shell/src/windows/WindowLoader\\.jsx$',
        '^tools/app-shell/src/lib/',
        '^tools/app-shell/src/utils/',
        '^tools/app-shell/vite\\.config\\.js$',
        '^tools/app-shell/vite-plugins/',
        '^tools/app-shell/public/',
      ],
    },
    {
      id: 'schema-forge-stack',
      kind: 'schema-forge-stack-package',
      scope: 'repo-infra',
      patterns: [
        '^packages/schema-forge-agent-context/',
        '^packages/schema-forge-stack/',
      ],
    },
    {
      id: 'domain-boundary-gate',
      kind: 'domain-boundary-gate',
      scope: 'repo-infra',
      patterns: [
        '^packages/schema-forge-core/bin/sf-domain-boundary-check\\.js$',
        '^packages/schema-forge-core/src/domain-boundary(?:/|$)',
        '^packages/schema-forge-core/src/domain-boundary-check\\.js$',
        '^packages/schema-forge-core/test/domain-boundary-check\\.test\\.js$',
      ],
    },
    {
      id: 'schema-forge-core',
      kind: 'schema-forge-core',
      scope: 'generator-change',
      patterns: ['^packages/schema-forge-core/'],
    },
    {
      id: 'root-sensitive',
      kind: 'root-global-sensitive',
      scope: 'root-global-sensitive',
      patterns: [
        '^package\\.json$',
        '^package-lock\\.json$',
        '^cli/cache/',
      ],
    },
    {
      id: 'repo-infra',
      kind: 'repo-infra',
      scope: 'repo-infra',
      patterns: [
        '^\\.github/',
        '^\\.githooks/',
        '^pipelines/',
        '^infra/',
        '^scripts/',
        '^Makefile$',
        '^sonar-project\\.properties$',
        '^schema_forge\\.properties$',
        '^ETENDO_VERSION$',
        '^\\.env\\.example$',
        '^\\.npmrc$',
        '^\\.nvmrc$',
        '^AGENTS\\.md$',
        '^CLAUDE\\.md$',
        '^opencode\\.json$',
      ],
    },
  ],
};
