import { useEffect, useCallback, useRef } from 'react';

/**
 * Hook to manage service worker registration and updates.
 *
 * - Registers the SW generated by vite-plugin-pwa
 * - Detects new versions and notifies via onUpdateAvailable
 * - Checks for updates when the tab regains focus
 * - Provides applyUpdate (skip waiting + reload) and clearCacheAndReload (nuke all caches)
 */
export function useServiceWorker({ onUpdateAvailable } = {}) {
  const registrationRef = useRef(null);
  const onUpdateRef = useRef(onUpdateAvailable);
  onUpdateRef.current = onUpdateAvailable;

  useEffect(() => {
    if (!('serviceWorker' in navigator)) return;

    navigator.serviceWorker
      .register('/sw.js')
      .then((registration) => {
        registrationRef.current = registration;

        registration.addEventListener('updatefound', () => {
          const newWorker = registration.installing;
          if (!newWorker) return;

          newWorker.addEventListener('statechange', () => {
            if (
              newWorker.state === 'installed' &&
              navigator.serviceWorker.controller
            ) {
              // A new version is waiting to activate
              onUpdateRef.current?.();
            }
          });
        });
      })
      .catch(() => {
        // SW registration failed — not critical, app works without it
      });

    function handleVisibilityChange() {
      if (
        document.visibilityState === 'visible' &&
        registrationRef.current
      ) {
        registrationRef.current.update();
      }
    }

    document.addEventListener('visibilitychange', handleVisibilityChange);
    return () => {
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, []);

  /** Tell the waiting SW to activate, then reload the page */
  const applyUpdate = useCallback(() => {
    const registration = registrationRef.current;
    if (registration?.waiting) {
      registration.waiting.postMessage({ type: 'SKIP_WAITING' });
    }
    window.location.reload();
  }, []);

  /** Delete every cache entry and unregister the SW, then reload */
  const clearCacheAndReload = useCallback(async () => {
    if ('caches' in window) {
      const cacheNames = await caches.keys();
      await Promise.all(cacheNames.map((name) => caches.delete(name)));
    }
    if (registrationRef.current) {
      await registrationRef.current.unregister();
    }
    window.location.reload();
  }, []);

  /** Manually trigger an update check (useful on route changes) */
  const checkForUpdate = useCallback(() => {
    registrationRef.current?.update();
  }, []);

  return { applyUpdate, clearCacheAndReload, checkForUpdate };
}
