import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';
import Handlebars from 'handlebars';
import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const templatesDir = resolve(__dirname, '../../templates');

async function compileTemplate(name) {
  const source = await readFile(resolve(templatesDir, name), 'utf8');
  return Handlebars.compile(source);
}

describe('Handlebars templates', () => {
  it('EventHandler.java.hbs compiles and generates valid Java', async () => {
    const template = await compileTemplate('EventHandler.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.salesorder',
      className: 'OrderDerivationHandler',
      entityName: 'Order',
      entityClass: 'org.openbravo.model.common.order.Order',
      schemaVersion: 'v1',
      schemaChecksum: 'a4b8c2d1',
      derivations: [
        { field: 'organization', getter: 'getOrganization', setter: 'setOrganization',
          type: 'fromConfig', source: 'OBContext.getOBContext().getCurrentOrganization()',
          checkNull: true }
      ]
    });
    assert.ok(result.includes('public class OrderDerivationHandler'));
    assert.ok(result.includes('GENERATED BY SCHEMA FORGE'));
    assert.ok(result.includes('setOrganization'));
  });

  it('DalProcess.java.hbs generates process with preconditions', async () => {
    const template = await compileTemplate('DalProcess.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.salesorder',
      className: 'CompleteOrderProcess',
      entityClass: 'org.openbravo.model.common.order.Order',
      preconditions: [
        { assertion: 'order.getOrderLineList().isEmpty()',
          negate: true, errorMessage: '@CannotCompleteWithoutLines@' }
      ],
      steps: [
        { name: 'assignDocumentNo', stub: false,
          code: 'order.setDocumentNo(FIN_Utility.getDocumentNo(...));' },
        { name: 'calculateTax', stub: true,
          comment: 'TODO(vertical-slice): implement tax calculation' }
      ]
    });
    assert.ok(result.includes('CompleteOrderProcess'));
    assert.ok(result.includes('CannotCompleteWithoutLines'));
    assert.ok(result.includes('TODO(vertical-slice)'));
  });

  it('DTO.java.hbs generates DTO with fields', async () => {
    const template = await compileTemplate('DTO.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.salesorder',
      className: 'OrderDTO',
      version: 1,
      fields: [
        { name: 'documentNo', type: 'String', getter: 'getDocumentNo', setter: 'setDocumentNo' },
        { name: 'dateOrdered', type: 'Date', getter: 'getDateOrdered', setter: 'setDateOrdered' }
      ]
    });
    assert.ok(result.includes('public class OrderDTO'));
    assert.ok(result.includes('getDocumentNo'));
    assert.ok(result.includes('setDateOrdered'));
  });

  it('RxEndpoint.java.hbs generates endpoint', async () => {
    const template = await compileTemplate('RxEndpoint.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.salesorder',
      className: 'OrderEndpoint',
      entityName: 'Order',
      entityClass: 'org.openbravo.model.common.order.Order',
      dtoClass: 'OrderDTO',
      filters: [
        { name: 'documentNo', type: 'String', column: 'documentNo' },
        { name: 'dateOrdered', type: 'Date', column: 'dateOrdered' }
      ]
    });
    assert.ok(result.includes('public class OrderEndpoint'));
    assert.ok(result.includes('documentNo'));
    assert.ok(result.includes('organization'));  // org-level filter RT-5
  });

  it('build.gradle.hbs generates valid gradle', async () => {
    const template = await compileTemplate('build.gradle.hbs');
    const result = template({
      moduleName: 'com.etendo.schemaforge.salesorder',
      etendoVersion: '24.1',
      dependencies: ['com.smf.jobs']
    });
    assert.ok(result.includes('com.etendo.schemaforge.salesorder'));
    assert.ok(result.includes('com.smf.jobs'));
  });

  it('dataset.xml.hbs generates valid XML', async () => {
    const template = await compileTemplate('dataset.xml.hbs');
    const result = template({
      moduleName: 'com.etendo.schemaforge.salesorder',
      records: [
        { table: 'AD_Process', uuid: 'ABC123', columns: [
          { name: 'Name', value: 'Complete Order' },
          { name: 'JavaClassName', value: 'com.etendo.schemaforge.salesorder.CompleteOrderProcess' }
        ]}
      ]
    });
    assert.ok(result.includes('<?xml'));
    assert.ok(result.includes('ABC123'));
    assert.ok(result.includes('Complete Order'));
  });

  it('ErrorSerializer.java.hbs compiles', async () => {
    const template = await compileTemplate('ErrorSerializer.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.salesorder',
      className: 'SalesOrderErrorSerializer'
    });
    assert.ok(result.includes('public class SalesOrderErrorSerializer'));
  });

  it('PreconditionValidator.java.hbs compiles', async () => {
    const template = await compileTemplate('PreconditionValidator.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.salesorder',
      className: 'OrderPreconditionValidator',
      entityClass: 'org.openbravo.model.common.order.Order',
      preconditions: [
        { assertion: 'order.getDocumentStatus().equals("DR")',
          negate: false, errorMessage: '@OrderMustBeDraft@' }
      ]
    });
    assert.ok(result.includes('OrderPreconditionValidator'));
    assert.ok(result.includes('OrderMustBeDraft'));
  });
});
