import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';
import Handlebars from 'handlebars';
import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const templatesDir = resolve(__dirname, '../../templates');

async function compileTemplate(name) {
  const source = await readFile(resolve(templatesDir, name), 'utf8');
  return Handlebars.compile(source);
}

describe('Handlebars templates — edge cases', () => {

  // EventHandler with empty derivations array
  it('EventHandler.java.hbs with empty derivations renders without derivation blocks', async () => {
    const template = await compileTemplate('EventHandler.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'EmptyDerivationHandler',
      entityName: 'Invoice',
      entityClass: 'org.openbravo.model.common.invoice.Invoice',
      schemaVersion: 'v2',
      schemaChecksum: 'deadbeef',
      derivations: []
    });
    assert.ok(result.includes('public class EmptyDerivationHandler'));
    assert.ok(result.includes('GENERATED BY SCHEMA FORGE'));
    // No derivation body: the #each block should produce no property assignments
    assert.ok(!result.includes('getProperty('));
  });

  // EventHandler with checkNull=false derivation
  it('EventHandler.java.hbs with checkNull=false omits null guard', async () => {
    const template = await compileTemplate('EventHandler.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'NoNullCheckHandler',
      entityName: 'Invoice',
      entityClass: 'org.openbravo.model.common.invoice.Invoice',
      schemaVersion: 'v1',
      schemaChecksum: 'abc123',
      derivations: [
        {
          field: 'currency',
          getter: 'getCurrency',
          setter: 'setCurrency',
          type: 'fromConfig',
          source: 'OBContext.getOBContext().getCurrentClient().getCurrency()',
          checkNull: false
        }
      ]
    });
    assert.ok(result.includes('setCurrency'));
    // When checkNull is false, there should be no null guard — no "if (derived != null)"
    assert.ok(!result.includes('if (derived != null)'));
    // The source must be assigned directly
    assert.ok(result.includes('OBContext.getOBContext().getCurrentClient().getCurrency()'));
  });

  // DalProcess with empty preconditions
  it('DalProcess.java.hbs with empty preconditions renders without precondition checks', async () => {
    const template = await compileTemplate('DalProcess.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'NoPreconditionProcess',
      entityClass: 'org.openbravo.model.common.order.Order',
      preconditions: [],
      steps: [
        { name: 'doWork', stub: false, code: 'order.setDocNo("X");' }
      ]
    });
    assert.ok(result.includes('NoPreconditionProcess'));
    // No OBException throw from preconditions
    assert.ok(!result.includes('throw new OBException'));
    assert.ok(result.includes('doWork'));
  });

  // DalProcess with empty steps
  it('DalProcess.java.hbs with empty steps renders without step blocks', async () => {
    const template = await compileTemplate('DalProcess.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'NoStepProcess',
      entityClass: 'org.openbravo.model.common.order.Order',
      preconditions: [
        { assertion: 'order == null', negate: false, errorMessage: '@OrderNotFound@' }
      ],
      steps: []
    });
    assert.ok(result.includes('NoStepProcess'));
    assert.ok(result.includes('OBDal.getInstance().flush()'));
    // With no steps, "Step:" comment should not appear
    assert.ok(!result.includes('// Step:'));
  });

  // DalProcess with all stub=true steps
  it('DalProcess.java.hbs with all stub=true steps renders only comments, no code', async () => {
    const template = await compileTemplate('DalProcess.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'AllStubProcess',
      entityClass: 'org.openbravo.model.common.order.Order',
      preconditions: [],
      steps: [
        { name: 'stepOne', stub: true, comment: 'TODO: implement step one' },
        { name: 'stepTwo', stub: true, comment: 'TODO: implement step two' }
      ]
    });
    assert.ok(result.includes('AllStubProcess'));
    assert.ok(result.includes('TODO: implement step one'));
    assert.ok(result.includes('TODO: implement step two'));
    // Stub steps should not emit executable code — no direct assignments
    assert.ok(!result.includes('order.set'));
  });

  // DTO with zero fields
  it('DTO.java.hbs with zero fields renders class with only constructor', async () => {
    const template = await compileTemplate('DTO.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'EmptyDTO',
      version: 3,
      fields: []
    });
    assert.ok(result.includes('public class EmptyDTO'));
    assert.ok(result.includes('private static final long serialVersionUID = 3L'));
    assert.ok(result.includes('public EmptyDTO()'));
    // No getters or setters should appear
    assert.ok(!result.includes('public void set'));
    assert.ok(!result.includes('return this.'));
  });

  // RxEndpoint with no filters
  it('RxEndpoint.java.hbs with no filters renders org-level filter only', async () => {
    const template = await compileTemplate('RxEndpoint.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'NoFilterEndpoint',
      entityName: 'Invoice',
      entityClass: 'org.openbravo.model.common.invoice.Invoice',
      dtoClass: 'InvoiceDTO',
      filters: []
    });
    assert.ok(result.includes('public class NoFilterEndpoint'));
    // RT-5 org-level filter must always be present
    assert.ok(result.includes('organization'));
    assert.ok(result.includes('getReadableOrganizations'));
    // No @QueryParam annotations since filters is empty
    assert.ok(!result.includes('@QueryParam'));
  });

  // dataset.xml with no records
  it('dataset.xml.hbs with no records renders valid XML shell', async () => {
    const template = await compileTemplate('dataset.xml.hbs');
    const result = template({
      moduleName: 'com.etendo.schemaforge.test',
      records: []
    });
    assert.ok(result.includes('<?xml'));
    assert.ok(result.includes('<data>'));
    assert.ok(result.includes('</data>'));
    assert.ok(result.includes('GENERATED BY SCHEMA FORGE'));
    // No table entries should be present
    assert.ok(!result.includes('<AD_'));
  });

  // PreconditionValidator with empty preconditions
  it('PreconditionValidator.java.hbs with empty preconditions renders valid class', async () => {
    const template = await compileTemplate('PreconditionValidator.java.hbs');
    const result = template({
      package: 'com.etendo.schemaforge.test',
      className: 'EmptyPreconditionValidator',
      entityClass: 'org.openbravo.model.common.order.Order',
      preconditions: []
    });
    assert.ok(result.includes('EmptyPreconditionValidator'));
    // Empty list means no errors added, so OBException should not be thrown
    // errors list is initialized, checked, and thrown only if non-empty
    assert.ok(result.includes('new ArrayList<>()'));
    assert.ok(result.includes('throw new OBException'));
    // No condition blocks for preconditions
    assert.ok(!result.includes('errors.add('));
  });

});
