// Auto-generated mock data - do not edit manually

export const header = [
  {
    "id": "mock-header-001",
    "documentNo": "HE-00001",
    "orderDate": "2026-01-15",
    "businessPartner": "Acme Corp",
    "partnerAddress": "Acme Corp",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "Main Warehouse",
    "documentStatus": "DR",
    "grandTotalAmount": 38907,
    "summedLineAmount": 38907,
    "currency": "USD",
    "orderReference": "Sample orderReference",
    "description": "Standard order for Q1 delivery",
    "deliveryStatus": "DR",
    "invoiceStatus": "DR"
  },
  {
    "id": "mock-header-002",
    "documentNo": "HE-00002",
    "orderDate": "2026-01-16",
    "businessPartner": "TechFlow Inc",
    "partnerAddress": "TechFlow Inc",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "East Distribution Center",
    "documentStatus": "CO",
    "grandTotalAmount": 9306,
    "summedLineAmount": 9306,
    "currency": "EUR",
    "orderReference": "Sample orderReference",
    "description": "Rush order - priority shipping required",
    "deliveryStatus": "CO",
    "invoiceStatus": "CO"
  },
  {
    "id": "mock-header-003",
    "documentNo": "HE-00003",
    "orderDate": "2026-01-17",
    "businessPartner": "Global Trade Ltd",
    "partnerAddress": "Global Trade Ltd",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "West Hub",
    "documentStatus": "VO",
    "grandTotalAmount": 11544,
    "summedLineAmount": 11544,
    "currency": "GBP",
    "orderReference": "Sample orderReference",
    "description": "Bulk purchase for warehouse restocking",
    "deliveryStatus": "VO",
    "invoiceStatus": "VO"
  },
  {
    "id": "mock-header-004",
    "documentNo": "HE-00004",
    "orderDate": "2026-01-18",
    "businessPartner": "Summit Industries",
    "partnerAddress": "Summit Industries",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "North Storage",
    "documentStatus": "IP",
    "grandTotalAmount": 11872,
    "summedLineAmount": 11872,
    "currency": "USD",
    "orderReference": "Sample orderReference",
    "description": "Sample order for client evaluation",
    "deliveryStatus": "IP",
    "invoiceStatus": "IP"
  },
  {
    "id": "mock-header-005",
    "documentNo": "HE-00005",
    "orderDate": "2026-01-19",
    "businessPartner": "Pacific Partners",
    "partnerAddress": "Pacific Partners",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "South Logistics",
    "documentStatus": "DR",
    "grandTotalAmount": 48460,
    "summedLineAmount": 48460,
    "currency": "EUR",
    "orderReference": "Sample orderReference",
    "description": "Recurring monthly supply order",
    "deliveryStatus": "DR",
    "invoiceStatus": "DR"
  },
  {
    "id": "mock-header-006",
    "documentNo": "HE-00006",
    "orderDate": "2026-01-20",
    "businessPartner": "Alpine Solutions",
    "partnerAddress": "Alpine Solutions",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "Central Depot",
    "documentStatus": "CO",
    "grandTotalAmount": 45418,
    "summedLineAmount": 45418,
    "currency": "GBP",
    "orderReference": "Sample orderReference",
    "description": "Special pricing agreement applies",
    "deliveryStatus": "CO",
    "invoiceStatus": "CO"
  },
  {
    "id": "mock-header-007",
    "documentNo": "HE-00007",
    "orderDate": "2026-01-21",
    "businessPartner": "Meridian Group",
    "partnerAddress": "Meridian Group",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "Regional Warehouse A",
    "documentStatus": "VO",
    "grandTotalAmount": 33840,
    "summedLineAmount": 33840,
    "currency": "USD",
    "orderReference": "Sample orderReference",
    "description": "Consolidated order from multiple requests",
    "deliveryStatus": "VO",
    "invoiceStatus": "VO"
  },
  {
    "id": "mock-header-008",
    "documentNo": "HE-00008",
    "orderDate": "2026-01-22",
    "businessPartner": "Vertex Systems",
    "partnerAddress": "Vertex Systems",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "Regional Warehouse B",
    "documentStatus": "IP",
    "grandTotalAmount": 25716,
    "summedLineAmount": 25716,
    "currency": "EUR",
    "orderReference": "Sample orderReference",
    "description": "Trial order for new product line",
    "deliveryStatus": "IP",
    "invoiceStatus": "IP"
  },
  {
    "id": "mock-header-009",
    "documentNo": "HE-00009",
    "orderDate": "2026-01-23",
    "businessPartner": "Atlas Manufacturing",
    "partnerAddress": "Atlas Manufacturing",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "Main Warehouse",
    "documentStatus": "DR",
    "grandTotalAmount": 44780,
    "summedLineAmount": 44780,
    "currency": "GBP",
    "orderReference": "Sample orderReference",
    "description": "Replacement for damaged goods",
    "deliveryStatus": "DR",
    "invoiceStatus": "DR"
  },
  {
    "id": "mock-header-010",
    "documentNo": "HE-00010",
    "orderDate": "2026-01-24",
    "businessPartner": "Nova Enterprises",
    "partnerAddress": "Nova Enterprises",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "East Distribution Center",
    "documentStatus": "CO",
    "grandTotalAmount": 12483,
    "summedLineAmount": 12483,
    "currency": "USD",
    "orderReference": "Sample orderReference",
    "description": "Pre-season inventory build-up",
    "deliveryStatus": "CO",
    "invoiceStatus": "CO"
  },
  {
    "id": "mock-header-011",
    "documentNo": "HE-00011",
    "orderDate": "2026-01-25",
    "businessPartner": "Pinnacle Services",
    "partnerAddress": "Pinnacle Services",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "West Hub",
    "documentStatus": "VO",
    "grandTotalAmount": 46022,
    "summedLineAmount": 46022,
    "currency": "EUR",
    "orderReference": "Sample orderReference",
    "description": "Customer-specific configuration",
    "deliveryStatus": "VO",
    "invoiceStatus": "VO"
  },
  {
    "id": "mock-header-012",
    "documentNo": "HE-00012",
    "orderDate": "2026-01-26",
    "businessPartner": "Horizon Labs",
    "partnerAddress": "Horizon Labs",
    "paymentMethod": "Sample paymentMethod",
    "warehouse": "North Storage",
    "documentStatus": "IP",
    "grandTotalAmount": 38634,
    "summedLineAmount": 38634,
    "currency": "GBP",
    "orderReference": "Sample orderReference",
    "description": "Government contract fulfillment",
    "deliveryStatus": "IP",
    "invoiceStatus": "IP"
  }
];

export const lines = [
  {
    "id": "mock-lines-001",
    "product": "Laptop Pro 15",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 38907,
    "tax": "VAT 21%",
    "discount": 6,
    "description": "Standard order for Q1 delivery",
    "headerId": "mock-header-001"
  },
  {
    "id": "mock-lines-002",
    "product": "USB-C Cable",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 9306,
    "tax": "VAT 10%",
    "discount": 21,
    "description": "Rush order - priority shipping required",
    "headerId": "mock-header-002"
  },
  {
    "id": "mock-lines-003",
    "product": "Wireless Mouse",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 11544,
    "tax": "VAT 0%",
    "discount": 0,
    "description": "Bulk purchase for warehouse restocking",
    "headerId": "mock-header-003"
  },
  {
    "id": "mock-lines-004",
    "product": "Mechanical Keyboard",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 11872,
    "tax": "Sales Tax 8.5%",
    "discount": 6,
    "description": "Sample order for client evaluation",
    "headerId": "mock-header-004"
  },
  {
    "id": "mock-lines-005",
    "product": "Monitor 27\"",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 48460,
    "tax": "Exempt",
    "discount": 14,
    "description": "Recurring monthly supply order",
    "headerId": "mock-header-005"
  },
  {
    "id": "mock-lines-006",
    "product": "Webcam HD",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 45418,
    "tax": "Reduced Rate 5%",
    "discount": 4,
    "description": "Special pricing agreement applies",
    "headerId": "mock-header-006"
  },
  {
    "id": "mock-lines-007",
    "product": "Headset Pro",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 33840,
    "tax": "Standard Rate 20%",
    "discount": 6,
    "description": "Consolidated order from multiple requests",
    "headerId": "mock-header-007"
  },
  {
    "id": "mock-lines-008",
    "product": "Docking Station",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 25716,
    "tax": "VAT 21%",
    "discount": 10,
    "description": "Trial order for new product line",
    "headerId": "mock-header-008"
  },
  {
    "id": "mock-lines-009",
    "product": "SSD 1TB",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 44780,
    "tax": "VAT 10%",
    "discount": 17,
    "description": "Replacement for damaged goods",
    "headerId": "mock-header-009"
  },
  {
    "id": "mock-lines-010",
    "product": "RAM 16GB",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 12483,
    "tax": "VAT 0%",
    "discount": 14,
    "description": "Pre-season inventory build-up",
    "headerId": "mock-header-010"
  },
  {
    "id": "mock-lines-011",
    "product": "Power Supply 750W",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 46022,
    "tax": "Sales Tax 8.5%",
    "discount": 19,
    "description": "Customer-specific configuration",
    "headerId": "mock-header-011"
  },
  {
    "id": "mock-lines-012",
    "product": "Network Switch",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 38634,
    "tax": "Exempt",
    "discount": 12,
    "description": "Government contract fulfillment",
    "headerId": "mock-header-012"
  }
];
