// Auto-generated mock data - do not edit manually

export const quotation = [
  {
    "id": "mock-quotation-001",
    "documentNo": "QU-00001",
    "orderDate": "2026-01-15",
    "businessPartner": "Acme Corp",
    "partnerAddress": "Acme Corp",
    "validUntil": "2026-01-15",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "DR",
    "grandTotalAmount": 38907,
    "summedLineAmount": 38907,
    "currency": "USD",
    "description": "Standard order for Q1 delivery"
  },
  {
    "id": "mock-quotation-002",
    "documentNo": "QU-00002",
    "orderDate": "2026-01-16",
    "businessPartner": "TechFlow Inc",
    "partnerAddress": "TechFlow Inc",
    "validUntil": "2026-01-16",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "CO",
    "grandTotalAmount": 9306,
    "summedLineAmount": 9306,
    "currency": "EUR",
    "description": "Rush order - priority shipping required"
  },
  {
    "id": "mock-quotation-003",
    "documentNo": "QU-00003",
    "orderDate": "2026-01-17",
    "businessPartner": "Global Trade Ltd",
    "partnerAddress": "Global Trade Ltd",
    "validUntil": "2026-01-17",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "VO",
    "grandTotalAmount": 11544,
    "summedLineAmount": 11544,
    "currency": "GBP",
    "description": "Bulk purchase for warehouse restocking"
  },
  {
    "id": "mock-quotation-004",
    "documentNo": "QU-00004",
    "orderDate": "2026-01-18",
    "businessPartner": "Summit Industries",
    "partnerAddress": "Summit Industries",
    "validUntil": "2026-01-18",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "IP",
    "grandTotalAmount": 11872,
    "summedLineAmount": 11872,
    "currency": "USD",
    "description": "Sample order for client evaluation"
  },
  {
    "id": "mock-quotation-005",
    "documentNo": "QU-00005",
    "orderDate": "2026-01-19",
    "businessPartner": "Pacific Partners",
    "partnerAddress": "Pacific Partners",
    "validUntil": "2026-01-19",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "DR",
    "grandTotalAmount": 48460,
    "summedLineAmount": 48460,
    "currency": "EUR",
    "description": "Recurring monthly supply order"
  },
  {
    "id": "mock-quotation-006",
    "documentNo": "QU-00006",
    "orderDate": "2026-01-20",
    "businessPartner": "Alpine Solutions",
    "partnerAddress": "Alpine Solutions",
    "validUntil": "2026-01-20",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "CO",
    "grandTotalAmount": 45418,
    "summedLineAmount": 45418,
    "currency": "GBP",
    "description": "Special pricing agreement applies"
  },
  {
    "id": "mock-quotation-007",
    "documentNo": "QU-00007",
    "orderDate": "2026-01-21",
    "businessPartner": "Meridian Group",
    "partnerAddress": "Meridian Group",
    "validUntil": "2026-01-21",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "VO",
    "grandTotalAmount": 33840,
    "summedLineAmount": 33840,
    "currency": "USD",
    "description": "Consolidated order from multiple requests"
  },
  {
    "id": "mock-quotation-008",
    "documentNo": "QU-00008",
    "orderDate": "2026-01-22",
    "businessPartner": "Vertex Systems",
    "partnerAddress": "Vertex Systems",
    "validUntil": "2026-01-22",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "IP",
    "grandTotalAmount": 25716,
    "summedLineAmount": 25716,
    "currency": "EUR",
    "description": "Trial order for new product line"
  },
  {
    "id": "mock-quotation-009",
    "documentNo": "QU-00009",
    "orderDate": "2026-01-23",
    "businessPartner": "Atlas Manufacturing",
    "partnerAddress": "Atlas Manufacturing",
    "validUntil": "2026-01-23",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "DR",
    "grandTotalAmount": 44780,
    "summedLineAmount": 44780,
    "currency": "GBP",
    "description": "Replacement for damaged goods"
  },
  {
    "id": "mock-quotation-010",
    "documentNo": "QU-00010",
    "orderDate": "2026-01-24",
    "businessPartner": "Nova Enterprises",
    "partnerAddress": "Nova Enterprises",
    "validUntil": "2026-01-24",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "CO",
    "grandTotalAmount": 12483,
    "summedLineAmount": 12483,
    "currency": "USD",
    "description": "Pre-season inventory build-up"
  },
  {
    "id": "mock-quotation-011",
    "documentNo": "QU-00011",
    "orderDate": "2026-01-25",
    "businessPartner": "Pinnacle Services",
    "partnerAddress": "Pinnacle Services",
    "validUntil": "2026-01-25",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "VO",
    "grandTotalAmount": 46022,
    "summedLineAmount": 46022,
    "currency": "EUR",
    "description": "Customer-specific configuration"
  },
  {
    "id": "mock-quotation-012",
    "documentNo": "QU-00012",
    "orderDate": "2026-01-26",
    "businessPartner": "Horizon Labs",
    "partnerAddress": "Horizon Labs",
    "validUntil": "2026-01-26",
    "paymentMethod": "Sample paymentMethod",
    "documentStatus": "IP",
    "grandTotalAmount": 38634,
    "summedLineAmount": 38634,
    "currency": "GBP",
    "description": "Government contract fulfillment"
  }
];

export const quotationLine = [
  {
    "id": "mock-quotationLine-001",
    "product": "Laptop Pro 15",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 38907,
    "tax": "VAT 21%",
    "discount": 6,
    "description": "Standard order for Q1 delivery",
    "quotationId": "mock-quotation-001"
  },
  {
    "id": "mock-quotationLine-002",
    "product": "USB-C Cable",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 9306,
    "tax": "VAT 10%",
    "discount": 21,
    "description": "Rush order - priority shipping required",
    "quotationId": "mock-quotation-002"
  },
  {
    "id": "mock-quotationLine-003",
    "product": "Wireless Mouse",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 11544,
    "tax": "VAT 0%",
    "discount": 0,
    "description": "Bulk purchase for warehouse restocking",
    "quotationId": "mock-quotation-003"
  },
  {
    "id": "mock-quotationLine-004",
    "product": "Mechanical Keyboard",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 11872,
    "tax": "Sales Tax 8.5%",
    "discount": 6,
    "description": "Sample order for client evaluation",
    "quotationId": "mock-quotation-004"
  },
  {
    "id": "mock-quotationLine-005",
    "product": "Monitor 27\"",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 48460,
    "tax": "Exempt",
    "discount": 14,
    "description": "Recurring monthly supply order",
    "quotationId": "mock-quotation-005"
  },
  {
    "id": "mock-quotationLine-006",
    "product": "Webcam HD",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 45418,
    "tax": "Reduced Rate 5%",
    "discount": 4,
    "description": "Special pricing agreement applies",
    "quotationId": "mock-quotation-006"
  },
  {
    "id": "mock-quotationLine-007",
    "product": "Headset Pro",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 33840,
    "tax": "Standard Rate 20%",
    "discount": 6,
    "description": "Consolidated order from multiple requests",
    "quotationId": "mock-quotation-007"
  },
  {
    "id": "mock-quotationLine-008",
    "product": "Docking Station",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 25716,
    "tax": "VAT 21%",
    "discount": 10,
    "description": "Trial order for new product line",
    "quotationId": "mock-quotation-008"
  },
  {
    "id": "mock-quotationLine-009",
    "product": "SSD 1TB",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 44780,
    "tax": "VAT 10%",
    "discount": 17,
    "description": "Replacement for damaged goods",
    "quotationId": "mock-quotation-009"
  },
  {
    "id": "mock-quotationLine-010",
    "product": "RAM 16GB",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 12483,
    "tax": "VAT 0%",
    "discount": 14,
    "description": "Pre-season inventory build-up",
    "quotationId": "mock-quotation-010"
  },
  {
    "id": "mock-quotationLine-011",
    "product": "Power Supply 750W",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 46022,
    "tax": "Sales Tax 8.5%",
    "discount": 19,
    "description": "Customer-specific configuration",
    "quotationId": "mock-quotation-011"
  },
  {
    "id": "mock-quotationLine-012",
    "product": "Network Switch",
    "orderedQuantity": "Sample orderedQuantity",
    "unitPrice": "Sample unitPrice",
    "lineNetAmount": 38634,
    "tax": "Exempt",
    "discount": 12,
    "description": "Government contract fulfillment",
    "quotationId": "mock-quotation-012"
  }
];
