/**
 * THE single definition of rendered-report i18n.
 *
 * The React UI is translated via `src/locales/*.json`, but the *rendered report*
 * (HTML preview, PDF, Excel, CSV) is Handlebars output, so it needs its own
 * strings. Two namespaces are injected into `meta`, deliberately kept apart so a
 * contract field named e.g. `total` can never shadow the generic "Total" chrome
 * text:
 *   meta.ui     — generic report chrome, same for every report.
 *   meta.labels — per-report labels resolved from the contract (columns, groups,
 *                 headerFields, parameters, plus an optional `labels` block for
 *                 strings that map to no column).
 *
 * Why this module exists: reports are rendered by TWO hand-written engines — the
 * Vite dev plugin in the functional repo (`tools/app-shell/vite-plugins/
 * report-api.js`) and the production report-server (`tools/report-server/
 * server.js`), which was created in 2026-04 as an explicit hand copy of the dev
 * one. This i18n layer (ETP-4898) was built in the DEV copy only. The server
 * kept resolving every label as `.en_US` and never even read the `locale` the
 * frontend was already sending, so every developer saw a translated report
 * locally while every server rendered blank column headers, empty label prefixes
 * and English titles — no error, no warning.
 *
 * That is the same failure mode as ETP-4899 (`report-descriptor.js`) and
 * ETP-4908, and the rule behind all three is the same: code that lives in a
 * shared module reaches production, code written inline in the dev plugin never
 * does. So the remedy here is one source of truth, imported by both engines —
 * NOT a copy plus a parity test. A parity test was tried for
 * `templates/reports/helpers/report-html-helpers.js` and the two copies drifted
 * anyway, because comparing field names cannot detect behavioural drift.
 *
 * If you add a UI string here, add it to EVERY locale below — a missing key
 * renders as empty text, not as a fallback.
 */

/** Generic report chrome, identical across every report. */
export const REPORT_UI_STRINGS = {
  en_US: { records: 'records', total: 'Total', totals: 'Totals', filters: 'Filters', generatedBy: 'Generated by Etendo Go', generatedOn: 'Generated on', printedOn: 'Printed on', page: 'Page', initialBalance: 'Initial Balance', subtotal: 'Subtotal', yes: 'Yes', no: 'No' },
  es_ES: { records: 'registros', total: 'Total', totals: 'Totales', filters: 'Filtros', generatedBy: 'Generado por Etendo Go', generatedOn: 'Generado el', printedOn: 'Impreso el', page: 'Página', initialBalance: 'Saldo inicial', subtotal: 'Subtotal', yes: 'Sí', no: 'No' },
};

/**
 * Return-variant overrides for report row VALUES (ETP-5013 follow-up), not
 * contract-declared chrome — a different problem from `REPORT_UI_STRINGS`
 * above. This used to be a full hand-copied dictionary of every
 * `C_DocType.DocBaseType` (Etendo's fixed AD_Ref_List 183) — replaced by a
 * real `LEFT JOIN ad_ref_list_trl` in Journal Entries' own SQL
 * (`report-contract.json`), via the `__REPORT_LOCALE__` placeholder
 * (`report-sql.js`), so the report's `document_type` column now arrives
 * ALREADY translated from Etendo's own source of truth — no more
 * hand-maintained list to drift from it (confirmed drift before this fix:
 * `BGT`/`ESH` were in the old dictionary but don't exist in `ad_ref_list` for
 * reference 183 in this environment; `MMP` was worded differently than the
 * real translation).
 *
 * `MMR`/`MMS` alone are still too coarse for a report row: both cover a
 * return variant (`C_DocType.IsReturn = 'Y'`) that means something different
 * from the regular receipt/shipment — "RTV Shipment" vs "MM Receipt", "RFC
 * Receipt" vs "MM Shipment" — and `IsReturn` has no equivalent code in
 * `ad_ref_list`, so it can't come from the JOIN. This tiny dictionary is what
 * remains hand-maintained, ONLY for that split; everything else comes from
 * the DB. Wording mirrors the /warehouse Transactions tab's own vocabulary
 * for the same distinction (`movTypeVendorReturn` "Vendor Return"/
 * "Devolución a proveedor", `movTypeCustomerReturn` "Customer Return"/
 * "Devolución de cliente") — the user's own reference example for this fix.
 */
export const RETURN_LABELS = {
  en_US: { MMR_RETURN: 'Vendor Return', MMS_RETURN: 'Customer Return' },
  es_ES: { MMR_RETURN: 'Devolución a proveedor', MMS_RETURN: 'Devolución de cliente' },
};

/** Resolve a {en_US, es_ES} label object for the requested locale. */
export function pickLabel(labelObj, locale, fallback = '') {
  return labelObj?.[locale] || labelObj?.en_US || fallback;
}

/** The chrome strings for a locale, falling back to English for unknown ones. */
export function pickUiStrings(locale) {
  return REPORT_UI_STRINGS[locale] || REPORT_UI_STRINGS.en_US;
}

/**
 * Flat map of every translatable label a contract declares, keyed by the name a
 * template refers to it by: column/group/headerField labels by `field`,
 * parameter labels by `name`, and any custom `contract.labels` key verbatim.
 */
export function buildContractLabels(contract, locale) {
  const labels = {};
  for (const c of contract.columns || []) {
    if (c.field) labels[c.field] = pickLabel(c.label, locale, c.field);
  }
  for (const g of contract.groups || []) {
    if (g.field) labels[g.field] = pickLabel(g.label, locale, g.field);
    for (const h of g.headerFields || []) {
      if (h.field) labels[h.field] = pickLabel(h.label, locale, h.field);
    }
  }
  for (const p of contract.parameters || []) {
    if (p.name) labels[p.name] = pickLabel(p.label, locale, p.name);
  }
  for (const [key, value] of Object.entries(contract.labels || {})) {
    labels[key] = pickLabel(value, locale, key);
  }
  return labels;
}
