/**
 * THE single definition of rendered-report i18n.
 *
 * The React UI is translated via `src/locales/*.json`, but the *rendered report*
 * (HTML preview, PDF, Excel, CSV) is Handlebars output, so it needs its own
 * strings. Two namespaces are injected into `meta`, deliberately kept apart so a
 * contract field named e.g. `total` can never shadow the generic "Total" chrome
 * text:
 *   meta.ui     — generic report chrome, same for every report.
 *   meta.labels — per-report labels resolved from the contract (columns, groups,
 *                 headerFields, parameters, plus an optional `labels` block for
 *                 strings that map to no column).
 *
 * Why this module exists: reports are rendered by TWO hand-written engines — the
 * Vite dev plugin in the functional repo (`tools/app-shell/vite-plugins/
 * report-api.js`) and the production report-server (`tools/report-server/
 * server.js`), which was created in 2026-04 as an explicit hand copy of the dev
 * one. This i18n layer (ETP-4898) was built in the DEV copy only. The server
 * kept resolving every label as `.en_US` and never even read the `locale` the
 * frontend was already sending, so every developer saw a translated report
 * locally while every server rendered blank column headers, empty label prefixes
 * and English titles — no error, no warning.
 *
 * That is the same failure mode as ETP-4899 (`report-descriptor.js`) and
 * ETP-4908, and the rule behind all three is the same: code that lives in a
 * shared module reaches production, code written inline in the dev plugin never
 * does. So the remedy here is one source of truth, imported by both engines —
 * NOT a copy plus a parity test. A parity test was tried for
 * `templates/reports/helpers/report-html-helpers.js` and the two copies drifted
 * anyway, because comparing field names cannot detect behavioural drift.
 *
 * If you add a UI string here, add it to EVERY locale below — a missing key
 * renders as empty text, not as a fallback.
 */

/** Generic report chrome, identical across every report. */
export const REPORT_UI_STRINGS = {
  en_US: { records: 'records', total: 'Total', totals: 'Totals', filters: 'Filters', generatedBy: 'Generated by Etendo Go', initialBalance: 'Initial Balance', subtotal: 'Subtotal' },
  es_ES: { records: 'registros', total: 'Total', totals: 'Totales', filters: 'Filtros', generatedBy: 'Generado por Etendo Go', initialBalance: 'Saldo inicial', subtotal: 'Subtotal' },
};

/** Resolve a {en_US, es_ES} label object for the requested locale. */
export function pickLabel(labelObj, locale, fallback = '') {
  return labelObj?.[locale] || labelObj?.en_US || fallback;
}

/** The chrome strings for a locale, falling back to English for unknown ones. */
export function pickUiStrings(locale) {
  return REPORT_UI_STRINGS[locale] || REPORT_UI_STRINGS.en_US;
}

/**
 * Flat map of every translatable label a contract declares, keyed by the name a
 * template refers to it by: column/group/headerField labels by `field`,
 * parameter labels by `name`, and any custom `contract.labels` key verbatim.
 */
export function buildContractLabels(contract, locale) {
  const labels = {};
  for (const c of contract.columns || []) {
    if (c.field) labels[c.field] = pickLabel(c.label, locale, c.field);
  }
  for (const g of contract.groups || []) {
    if (g.field) labels[g.field] = pickLabel(g.label, locale, g.field);
    for (const h of g.headerFields || []) {
      if (h.field) labels[h.field] = pickLabel(h.label, locale, h.field);
    }
  }
  for (const p of contract.parameters || []) {
    if (p.name) labels[p.name] = pickLabel(p.label, locale, p.name);
  }
  for (const [key, value] of Object.entries(contract.labels || {})) {
    labels[key] = pickLabel(value, locale, key);
  }
  return labels;
}
